import type { Locale } from "@/lib/locale";

// Text of the demos in lessons 2–4 of "How it works". Example news below is invented for the exercise and says so.

const en = {
  editor: {
    title: "You are the editor",
    intro: "Three drafts written by the AI. The source is on the left of each one. Approve or reject — then see what a careful editor would do. (The news here is invented for this exercise.)",
    source: "Source",
    draft: "AI draft",
    approve: "Approve",
    reject: "Reject",
    good: "Good call.",
    bad: "Look again.",
    score: "You made {n} of {total} right calls",
    items: [
      {
        source: "Heavy rain flooded 12 houses in a mountain village. Officials said no one was hurt.",
        draft: "Heavy rain flooded 120 houses in a mountain village. Officials say no one was hurt.",
        approve: false,
        why: "The draft says 120 houses, the source says 12. One extra zero — and the channel would spread a false number.",
      },
      {
        source: "The city opened a new public library with 20,000 books on Monday.",
        draft: "A new public library with 20,000 books opened in the city on Monday.",
        approve: true,
        why: "Every fact matches the source, nothing is added. This one can go out.",
      },
      {
        source: "A bakery chain raised the price of bread by 5%.",
        draft: "Bread is getting much more expensive everywhere — a disaster for families!",
        approve: false,
        why: "The source is about one bakery chain and 5%. “Everywhere” and “disaster” are not facts — the model added drama.",
      },
    ],
  },
  letters: {
    title: "The letter check",
    intro: "The channel is in Russian. Paste or type any text and see what the automatic check decides.",
    label: "Text from the model",
    examples: "Examples",
    exampleNames: ["Russian post", "Model thinking out loud", "Tajik text"],
    exampleTexts: [
      "В Душанбе открылась новая библиотека на 20 000 книг. Вход свободный.",
      "Okay, the user wants a post in Russian. Let me think about the structure first.",
      "Ҳуҷҷатҳои ҳисоботӣ ҷамъ шуданд ва ба ҳамаи шарикон фиристода шуданд.",
    ],
    letters: "Letters",
    russian: "Russian letters",
    share: "Share",
    pass: "Looks like a Russian post — goes to the editor.",
    fail: "Less than half are Russian letters — rejected, the next model is asked.",
  },
  chain: {
    title: "The fallback chain",
    intro: "Free AI models are sometimes overloaded or answer in the wrong language. Set what each model does today and press the button.",
    models: ["Model A", "Model B", "Model C"],
    states: { ok: "works", busy: "overloaded", english: "answers in English" },
    run: "Write the post",
    log: { ok: "wrote the post ✓", busy: "is overloaded — trying the next one", english: "answered in English — the letter check rejected it" },
    none: "All models are unavailable — the editor sees “try again in a few minutes”, and nothing wrong is published.",
  },
  nominal: {
    title: "The nominal trap",
    intro: "The National Bank publishes some rates per 10 or 100 units. Pick a currency and an amount.",
    currency: "Currency",
    amount: "Amount",
    published: "The bank publishes",
    wrong: "Forgot the nominal",
    right: "Correct",
    note: "Official rates of the National Bank of Tajikistan for 2 October 2026. Today's rates: kursi-tojik.pages.dev",
  },
  outage: {
    title: "When the source goes down",
    toggle: "The bank's website is down",
    naive: "Site A asks the bank on every visit",
    cached: "Site B reads its own saved copy",
    naiveOk: "USD = 9.2331 TJS",
    naiveDown: "Error: could not load the rates",
    cachedValue: "USD = 9.2331 TJS",
    cachedNote: "official rate for 2 October 2026 · source nbt.tj",
    cachedDownNote: "The bank is down, so this is the last saved official rate — with its date. The collector will try again in 3 hours.",
  },
  access: {
    title: "Who may do what",
    role: "Who is asking",
    roles: { visitor: "Visitor (not logged in)", member: "Member", editor: "Editor", admin: "Administrator" },
    action: "What they try",
    actions: {
      readPublic: "Read a public news post",
      readMembers: "Read a members-only document",
      writePost: "Publish a news post",
      readInbox: "Read the contact-form inbox",
      makeAdmin: "Make themselves an administrator",
    },
    rulesIn: "Where the rules live",
    inApp: "Only in the app",
    inDb: "In the database",
    viaApp: "Use the app",
    viaApi: "Send a request straight to the database",
    results: {
      allowed: "✓ Allowed — this role may do it.",
      hidden: "The app simply has no button for it. Looks safe… but is it? Try sending the request directly.",
      refused: "✗ Refused by the database. No screen or script can get around this rule.",
      leaked: "⚠ It worked! The app hid the button, but the database answers anyone. The data has leaked.",
    },
  },
  link: {
    title: "A link that expires",
    intro: "Members-only documents are downloaded through a link that works for 60 seconds.",
    get: "Get the download link",
    open: "Open the link",
    skip: "Skip 30 seconds",
    left: "Works for {s} more seconds",
    expired: "Expired",
    ok: "✓ report.pdf is downloading.",
    denied: "✗ 403 — this link has expired. Log in and get a new one.",
  },
  slowNet: {
    title: "How long does this page take?",
    intro: "Choose a connection and compare the full version of this site's home page with its light version. The sizes are real, measured from this site; the time is a rough estimate.",
    network: "Connection",
    networks: { "4g": "4G", "3g": "3G", "2g": "2G" },
    speeds: { "4g": "10 Mbit/s, 50 ms delay", "3g": "700 kbit/s, 270 ms delay", "2g": "70 kbit/s, 1.4 s delay" },
    parts: { html: "The page itself (HTML)", css: "Styles (CSS)", fonts: "Fonts", js: "JavaScript", photos: "Photos" },
    kb: "{n} KB",
    loads: "loads",
    waits: "waits for a tap",
    inLite: "In the light version",
    full: "Full version",
    lite: "Light version",
    seconds: "≈ {n} s",
    saved: "The light version is ready {n} times sooner and downloads {kb} KB less.",
    yours: "Your browser says: connection {type}{saver}.",
    saver: ", data saver on",
    unknown: "Your browser does not report its connection (Safari and Firefox keep it private). This site then shows the full version — and you can switch to the light one in the footer.",
  },
  knowledge: {
    title: "Ask the café's bot",
    intro: "This bot belongs to an invented café, “Navruz”. It knows only what is written on four cards. Ask a question and watch how it finds the answer.",
    kb: "What the bot knows",
    cards: [
      { id: "menu", title: "Menu and prices", text: "Plov costs {price} somoni, salad 15 somoni, tea 5 somoni." },
      { id: "delivery", title: "Delivery", text: "We deliver across Dushanbe from 10:00 to 22:00. Delivery is free from 100 somoni." },
      { id: "hours", title: "Opening hours", text: "We are open every day from 9:00 to 23:00." },
      { id: "payment", title: "Payment", text: "We accept cash and bank cards." },
    ],
    stop: ["the", "and", "you", "how", "much", "what", "does", "are", "your", "for", "can", "from", "when", "there", "have", "with", "this", "that"],
    presets: ["How much does plov cost?", "Do you deliver to my home?", "When are you open?", "Can I pay by card?", "Is there a helicopter pad?"],
    expect: ["menu", "delivery", "hours", "payment", null],
    price: "Change the price of plov",
    ask: "Ask",
    placeholder: "Type your own question…",
    steps: ["Words of the question", "Search the cards", "Answer"],
    match: "{n}% match",
    source: "Answer taken from: {card}",
    unknown: "I'm not sure — I'll pass your question to a manager.",
    unknownWhy: "No card matched well enough, so the bot does not make anything up.",
    note: "Real bots compare the meaning of words, not just their letters. The idea is the same: find the right card first, then answer from it.",
  },
};

export type LessonStrings = typeof en;

const ru: LessonStrings = {
  editor: {
    title: "Вы — редактор",
    intro: "Три черновика, написанных ИИ. У каждого есть источник. Одобрите или отклоните — и посмотрите, что сделал бы внимательный редактор. (Новости здесь придуманы для упражнения.)",
    source: "Источник",
    draft: "Черновик ИИ",
    approve: "Одобрить",
    reject: "Отклонить",
    good: "Верное решение.",
    bad: "Посмотрите ещё раз.",
    score: "Верных решений: {n} из {total}",
    items: [
      {
        source: "Сильный дождь затопил 12 домов в горном селе. По словам властей, никто не пострадал.",
        draft: "Сильный дождь затопил 120 домов в горном селе. Власти сообщают, что никто не пострадал.",
        approve: false,
        why: "В черновике 120 домов, в источнике — 12. Один лишний ноль — и канал разнёс бы неправду.",
      },
      {
        source: "В понедельник в городе открылась новая публичная библиотека на 20 000 книг.",
        draft: "В понедельник в городе открылась новая публичная библиотека на 20 000 книг.",
        approve: true,
        why: "Каждый факт совпадает с источником, ничего не добавлено. Можно публиковать.",
      },
      {
        source: "Сеть пекарен подняла цену хлеба на 5%.",
        draft: "Хлеб резко дорожает повсюду — настоящая беда для семей!",
        approve: false,
        why: "В источнике — одна сеть пекарен и 5%. «Повсюду» и «беда» — не факты: модель добавила драмы.",
      },
    ],
  },
  letters: {
    title: "Проверка букв",
    intro: "Канал на русском языке. Вставьте или напишите любой текст и посмотрите, что решит автоматическая проверка.",
    label: "Текст от модели",
    examples: "Примеры",
    exampleNames: ["Пост на русском", "Модель думает вслух", "Текст на таджикском"],
    exampleTexts: en.letters.exampleTexts,
    letters: "Букв",
    russian: "Русских букв",
    share: "Доля",
    pass: "Похоже на русский пост — уходит редактору.",
    fail: "Русских букв меньше половины — ответ отклонён, спрашиваем следующую модель.",
  },
  chain: {
    title: "Цепочка запасных моделей",
    intro: "Бесплатные модели ИИ иногда перегружены или отвечают не на том языке. Задайте, что каждая модель делает сегодня, и нажмите кнопку.",
    models: ["Модель A", "Модель B", "Модель C"],
    states: { ok: "работает", busy: "перегружена", english: "отвечает по-английски" },
    run: "Написать пост",
    log: { ok: "написала пост ✓", busy: "перегружена — пробуем следующую", english: "ответила по-английски — проверка букв её отклонила" },
    none: "Все модели недоступны — редактор видит «попробуй через пару минут», и ничего неправильного не публикуется.",
  },
  nominal: {
    title: "Ловушка номинала",
    intro: "Нацбанк публикует некоторые курсы за 10 или 100 единиц. Выберите валюту и сумму.",
    currency: "Валюта",
    amount: "Сумма",
    published: "Банк публикует",
    wrong: "Забыли номинал",
    right: "Правильно",
    note: "Официальные курсы Национального банка Таджикистана на 2 октября 2026 года. Сегодняшние курсы: kursi-tojik.pages.dev",
  },
  outage: {
    title: "Когда источник падает",
    toggle: "Сайт банка не работает",
    naive: "Сайт А спрашивает банк при каждом посещении",
    cached: "Сайт Б читает свою сохранённую копию",
    naiveOk: "USD = 9,2331 TJS",
    naiveDown: "Ошибка: не удалось загрузить курсы",
    cachedValue: "USD = 9,2331 TJS",
    cachedNote: "официальный курс на 2 октября 2026 · источник nbt.tj",
    cachedDownNote: "Банк не отвечает, поэтому показан последний сохранённый официальный курс — с датой. Сборщик попробует снова через 3 часа.",
  },
  access: {
    title: "Кто что может",
    role: "Кто спрашивает",
    roles: { visitor: "Посетитель (не вошёл)", member: "Участник", editor: "Редактор", admin: "Администратор" },
    action: "Что пытается сделать",
    actions: {
      readPublic: "Прочитать публичную новость",
      readMembers: "Прочитать документ только для участников",
      writePost: "Опубликовать новость",
      readInbox: "Прочитать письма из формы обратной связи",
      makeAdmin: "Сделать себя администратором",
    },
    rulesIn: "Где живут правила",
    inApp: "Только в приложении",
    inDb: "В базе данных",
    viaApp: "Через приложение",
    viaApi: "Отправить запрос прямо в базу",
    results: {
      allowed: "✓ Разрешено — этой роли можно.",
      hidden: "В приложении просто нет такой кнопки. Выглядит безопасно… но так ли это? Попробуйте отправить запрос напрямую.",
      refused: "✗ База данных отказала. Никакой экран или скрипт не обойдёт это правило.",
      leaked: "⚠ Получилось! Приложение спрятало кнопку, но база отвечает всем. Данные утекли.",
    },
  },
  link: {
    title: "Ссылка, которая сгорает",
    intro: "Документы для участников скачиваются по ссылке, которая работает 60 секунд.",
    get: "Получить ссылку на скачивание",
    open: "Открыть ссылку",
    skip: "Перемотать 30 секунд",
    left: "Работает ещё {s} с",
    expired: "Срок истёк",
    ok: "✓ report.pdf скачивается.",
    denied: "✗ 403 — срок ссылки истёк. Войдите и получите новую.",
  },
  slowNet: {
    title: "Сколько грузится эта страница?",
    intro: "Выберите связь и сравните полную версию главной страницы этого сайта с облегчённой. Размеры настоящие, измерены на этом сайте; время — примерная оценка.",
    network: "Связь",
    networks: { "4g": "4G", "3g": "3G", "2g": "2G" },
    speeds: { "4g": "10 Мбит/с, задержка 50 мс", "3g": "700 кбит/с, задержка 270 мс", "2g": "70 кбит/с, задержка 1,4 с" },
    parts: { html: "Сама страница (HTML)", css: "Стили (CSS)", fonts: "Шрифты", js: "JavaScript", photos: "Фото" },
    kb: "{n} КБ",
    loads: "загружается",
    waits: "ждёт нажатия",
    inLite: "В облегчённой версии",
    full: "Полная версия",
    lite: "Облегчённая версия",
    seconds: "≈ {n} с",
    saved: "Облегчённая версия готова в {n} раза быстрее и скачивает на {kb} КБ меньше.",
    yours: "Ваш браузер сообщает: связь {type}{saver}.",
    saver: ", включена экономия трафика",
    unknown: "Ваш браузер не сообщает о своей связи (Safari и Firefox это скрывают). Тогда сайт показывает полную версию — а облегчённую можно включить внизу страницы.",
  },
  knowledge: {
    title: "Спросите бота кафе",
    intro: "Это бот выдуманного кафе «Навруз». Он знает только то, что написано на четырёх карточках. Задайте вопрос и посмотрите, как он находит ответ.",
    kb: "Что знает бот",
    cards: [
      { id: "menu", title: "Меню и цены", text: "Плов стоит {price} сомони, салат — 15 сомони, чай — 5 сомони." },
      { id: "delivery", title: "Доставка", text: "Доставляем по Душанбе с 10:00 до 22:00. Доставка бесплатная от 100 сомони." },
      { id: "hours", title: "Часы работы", text: "Мы открыты каждый день с 9:00 до 23:00." },
      { id: "payment", title: "Оплата", text: "Принимаем наличные и банковские карты." },
    ],
    stop: ["что", "как", "где", "когда", "сколько", "есть", "вас", "для", "можно", "мне", "это", "или", "при"],
    presets: ["Сколько стоит плов?", "Вы доставляете на дом?", "Во сколько вы открываетесь?", "Можно оплатить картой?", "Есть ли у вас парковка для вертолёта?"],
    expect: ["menu", "delivery", "hours", "payment", null],
    price: "Измените цену плова",
    ask: "Спросить",
    placeholder: "Напишите свой вопрос…",
    steps: ["Слова вопроса", "Поиск по карточкам", "Ответ"],
    match: "совпадение {n}%",
    source: "Ответ взят из карточки: {card}",
    unknown: "Не знаю точно — передам ваш вопрос менеджеру.",
    unknownWhy: "Ни одна карточка не подошла, поэтому бот ничего не выдумывает.",
    note: "Настоящие боты сравнивают смысл слов, а не только буквы. Но идея та же: сначала найти нужную карточку, потом ответить по ней.",
  },
};

const tj: LessonStrings = {
  editor: {
    title: "Шумо муҳаррир ҳастед",
    intro: "Се лоиҳае, ки зеҳни сунъӣ навиштааст. Ҳар кадом манбаъ дорад. Тасдиқ ё рад кунед — ва бинед, ки муҳаррири бодиққат чӣ мекард. (Хабарҳо барои машқ сохта шудаанд.)",
    source: "Манбаъ",
    draft: "Лоиҳаи зеҳни сунъӣ",
    approve: "Тасдиқ",
    reject: "Рад",
    good: "Қарори дуруст.",
    bad: "Боз як бор нигоҳ кунед.",
    score: "Қарорҳои дуруст: {n} аз {total}",
    items: [
      {
        source: "Борони шадид дар як деҳаи кӯҳӣ 12 хонаро зери об монд. Ба гуфтаи мақомот, ба касе осеб нарасид.",
        draft: "Борони шадид дар як деҳаи кӯҳӣ 120 хонаро зери об монд. Мақомот мегӯянд, ки ба касе осеб нарасид.",
        approve: false,
        why: "Дар лоиҳа 120 хона, дар манбаъ — 12. Як сифри зиёдатӣ — ва канал хабари нодуруст паҳн мекард.",
      },
      {
        source: "Рӯзи душанбе дар шаҳр китобхонаи нави оммавӣ бо 20 000 китоб кушода шуд.",
        draft: "Рӯзи душанбе дар шаҳр китобхонаи нави оммавӣ бо 20 000 китоб кушода шуд.",
        approve: true,
        why: "Ҳар далел бо манбаъ мувофиқ аст, чизе илова нашудааст. Нашр кардан мумкин аст.",
      },
      {
        source: "Як шабакаи нонвойхонаҳо нархи нонро 5% боло бурд.",
        draft: "Нон дар ҳама ҷо якбора гарон мешавад — фалокат барои оилаҳо!",
        approve: false,
        why: "Дар манбаъ — як шабакаи нонвойхона ва 5%. «Дар ҳама ҷо» ва «фалокат» далел нестанд: модел драма илова кард.",
      },
    ],
  },
  letters: {
    title: "Санҷиши ҳарфҳо",
    intro: "Канал бо забони русӣ аст. Ҳар матнро гузоред ё нависед ва бинед, ки санҷиши худкор чӣ қарор медиҳад.",
    label: "Матн аз модел",
    examples: "Намунаҳо",
    exampleNames: ["Пости русӣ", "Модел бо овози баланд фикр мекунад", "Матни тоҷикӣ"],
    exampleTexts: en.letters.exampleTexts,
    letters: "Ҳарфҳо",
    russian: "Ҳарфҳои русӣ",
    share: "Ҳисса",
    pass: "Ба пости русӣ монанд аст — ба муҳаррир меравад.",
    fail: "Ҳарфҳои русӣ камтар аз нисф — ҷавоб рад шуд, аз модели навбатӣ мепурсем.",
  },
  chain: {
    title: "Занҷири моделҳои эҳтиётӣ",
    intro: "Моделҳои ройгони зеҳни сунъӣ баъзан серборанд ё бо забони дигар ҷавоб медиҳанд. Муайян кунед, ки ҳар модел имрӯз чӣ мекунад, ва тугмаро пахш кунед.",
    models: ["Модели A", "Модели B", "Модели C"],
    states: { ok: "кор мекунад", busy: "сербор аст", english: "ба англисӣ ҷавоб медиҳад" },
    run: "Постро нависед",
    log: { ok: "постро навишт ✓", busy: "сербор аст — навбатиро месанҷем", english: "ба англисӣ ҷавоб дод — санҷиши ҳарфҳо онро рад кард" },
    none: "Ҳамаи моделҳо дастнорасанд — муҳаррир «баъд аз чанд дақиқа кӯшиш кунед»-ро мебинад ва ҳеҷ чизи нодуруст нашр намешавад.",
  },
  nominal: {
    title: "Доми номинал",
    intro: "Бонки миллӣ баъзе қурбҳоро барои 10 ё 100 воҳид нашр мекунад. Асъор ва маблағро интихоб кунед.",
    currency: "Асъор",
    amount: "Маблағ",
    published: "Бонк нашр мекунад",
    wrong: "Номинал фаромӯш шуд",
    right: "Дуруст",
    note: "Қурбҳои расмии Бонки миллии Тоҷикистон барои 2 октябри соли 2026. Қурбҳои имрӯза: kursi-tojik.pages.dev",
  },
  outage: {
    title: "Вақте манбаъ кор намекунад",
    toggle: "Сайти бонк кор намекунад",
    naive: "Сайти А ҳар бор аз бонк мепурсад",
    cached: "Сайти Б нусхаи захирашудаи худро мехонад",
    naiveOk: "USD = 9,2331 TJS",
    naiveDown: "Хато: қурбҳо бор нашуданд",
    cachedValue: "USD = 9,2331 TJS",
    cachedNote: "қурби расмӣ барои 2 октябри 2026 · манбаъ nbt.tj",
    cachedDownNote: "Бонк ҷавоб намедиҳад, барои ҳамин охирин қурби расмии захирашуда — бо санааш нишон дода мешавад. Ҷамъкунанда баъд аз 3 соат боз кӯшиш мекунад.",
  },
  access: {
    title: "Кӣ чӣ карда метавонад",
    role: "Кӣ мепурсад",
    roles: { visitor: "Меҳмон (ворид нашудааст)", member: "Аъзо", editor: "Муҳаррир", admin: "Маъмур" },
    action: "Чӣ кардан мехоҳад",
    actions: {
      readPublic: "Хабари оммавиро хондан",
      readMembers: "Ҳуҷҷати махсуси аъзоёнро хондан",
      writePost: "Хабар нашр кардан",
      readInbox: "Номаҳои шакли тамосро хондан",
      makeAdmin: "Худро маъмур кардан",
    },
    rulesIn: "Қоидаҳо дар куҷоянд",
    inApp: "Фақат дар барнома",
    inDb: "Дар пойгоҳи додаҳо",
    viaApp: "Тавассути барнома",
    viaApi: "Дархостро рост ба пойгоҳ фиристодан",
    results: {
      allowed: "✓ Иҷозат аст — ба ин нақш мумкин аст.",
      hidden: "Дар барнома чунин тугма нест. Бехатар менамояд… аммо ҳамин тавр аст? Дархостро мустақим фиристед.",
      refused: "✗ Пойгоҳи додаҳо рад кард. Ҳеҷ экран ё скрипт ин қоидаро давр зада наметавонад.",
      leaked: "⚠ Шуд! Барнома тугмаро пинҳон кард, аммо пойгоҳ ба ҳама ҷавоб медиҳад. Додаҳо фош шуданд.",
    },
  },
  link: {
    title: "Пайванде, ки месӯзад",
    intro: "Ҳуҷҷатҳои аъзоён тавассути пайванде зеркашӣ мешаванд, ки 60 сония кор мекунад.",
    get: "Пайванди зеркаширо гирифтан",
    open: "Пайвандро кушодан",
    skip: "30 сония пеш гузарондан",
    left: "Боз {s} сония кор мекунад",
    expired: "Мӯҳлат гузашт",
    ok: "✓ report.pdf зеркашӣ мешавад.",
    denied: "✗ 403 — мӯҳлати пайванд гузашт. Ворид шавед ва пайванди нав гиред.",
  },
  slowNet: {
    title: "Ин саҳифа чанд вақт бор мешавад?",
    intro: "Пайвастро интихоб кунед ва версияи пурраи саҳифаи асосии ин сайтро бо версияи сабук муқоиса кунед. Андозаҳо воқеӣ мебошанд, аз ҳамин сайт чен карда шудаанд; вақт тахминӣ аст.",
    network: "Пайваст",
    networks: { "4g": "4G", "3g": "3G", "2g": "2G" },
    speeds: { "4g": "10 Мбит/с, таъхир 50 мс", "3g": "700 кбит/с, таъхир 270 мс", "2g": "70 кбит/с, таъхир 1,4 с" },
    parts: { html: "Худи саҳифа (HTML)", css: "Услубҳо (CSS)", fonts: "Ҳарфҳо (шрифтҳо)", js: "JavaScript", photos: "Суратҳо" },
    kb: "{n} КБ",
    loads: "бор мешавад",
    waits: "пахшро интизор аст",
    inLite: "Дар версияи сабук",
    full: "Версияи пурра",
    lite: "Версияи сабук",
    seconds: "≈ {n} с",
    saved: "Версияи сабук {n} маротиба зудтар тайёр мешавад ва {kb} КБ камтар зеркашӣ мекунад.",
    yours: "Браузери шумо мегӯяд: пайваст {type}{saver}.",
    saver: ", сарфаи трафик фаъол аст",
    unknown: "Браузери шумо дар бораи пайвасташ хабар намедиҳад (Safari ва Firefox инро пинҳон медоранд). Он гоҳ сайт версияи пурраро нишон медиҳад — версияи сабукро дар поёни саҳифа фаъол кардан мумкин аст.",
  },
  knowledge: {
    title: "Аз боти қаҳвахона пурсед",
    intro: "Ин боти қаҳвахонаи хаёлии «Наврӯз» аст. Вай танҳо он чизеро медонад, ки дар чор корт навишта шудааст. Савол диҳед ва бинед, ки ҷавобро чӣ тавр меёбад.",
    kb: "Бот чиро медонад",
    cards: [
      { id: "menu", title: "Меню ва нархҳо", text: "Палав {price} сомонӣ, салат 15 сомонӣ, чой 5 сомонӣ." },
      { id: "delivery", title: "Расонидан", text: "Дар Душанбе аз соати 10:00 то 22:00 мерасонем. Аз 100 сомонӣ расонидан ройгон аст." },
      { id: "hours", title: "Соатҳои корӣ", text: "Мо ҳар рӯз аз соати 9:00 то 23:00 кушодаем." },
      { id: "payment", title: "Пардохт", text: "Пули нақд ва кортҳои бонкиро қабул мекунем." },
    ],
    stop: ["чанд", "аст", "шумо", "кадом", "ҳаст", "барои", "мумкин", "кардан", "кай", "ҷои"],
    presets: ["Палав чанд пул аст?", "Шумо ба хона мерасонед?", "Соатҳои кории шумо кадом аст?", "Бо корт пардохт кардан мумкин?", "Барои чархбол ҷои истгоҳ ҳаст?"],
    expect: ["menu", "delivery", "hours", "payment", null],
    price: "Нархи палавро иваз кунед",
    ask: "Пурсидан",
    placeholder: "Саволи худро нависед…",
    steps: ["Калимаҳои савол", "Ҷустуҷӯ дар кортҳо", "Ҷавоб"],
    match: "мувофиқат {n}%",
    source: "Ҷавоб аз корт гирифта шуд: {card}",
    unknown: "Аниқ намедонам — саволатонро ба менеҷер мефиристам.",
    unknownWhy: "Ҳеҷ корт мувофиқ наомад, барои ҳамин бот чизе намебофад.",
    note: "Ботҳои воқеӣ маънои калимаҳоро муқоиса мекунанд, на танҳо ҳарфҳоро. Аммо ғоя ҳамон аст: аввал корти лозимиро ёфтан, баъд аз рӯи он ҷавоб додан.",
  },
};

export const lessonStrings: Record<Locale, LessonStrings> = { en, ru, tj };
