import type { Locale } from "@/lib/locale";

// Text of the interactive blog demos. Lives next to them so the article pages do not load the whole site dictionary.

const en = {
  demo: "Try it",
  flow: {
    title: "A message's journey",
    pick: "Message to send",
    stations: { you: "You", telegram: "Telegram", bot: "Bot server", db: "Database" },
    prev: "Back",
    next: "Next step",
    play: "Play",
    pause: "Pause",
    restart: "Start again",
    step: "Step {n} of {total}",
    messages: [
      { text: "/start", reply: "Hello! I am the shop bot. Choose: 🛒 Catalogue · 📞 Contact", rule: "the /start command → greeting with buttons" },
      { text: "100 usd", reply: "100 USD — got it. Which currency should I convert it to?", rule: "a number + a currency word → amount" },
      { text: "Hi!", reply: "Hi! Type /start to see what I can do.", rule: "no rule matched → polite default answer" },
    ],
    steps: [
      "You press Send. Your phone sends the text to Telegram's servers — not to the bot directly.",
      "Telegram wraps the text in an “update”: who sent it, from which chat, when. It hands the update to the bot's server.",
      "The bot checks its notebook — the database: who is this person, which language do they speak, what did they do last time?",
      "Now the bot's code decides. It goes through its rules from top to bottom and takes the first one that fits.",
      "The bot asks Telegram to deliver the answer: it calls the sendMessage method with the chat number and the text.",
      "Telegram delivers the answer to your phone. All of this usually takes less than a second.",
    ],
  },
  playground: {
    title: "Build your own bot",
    rulesLabel: "Rules — the bot checks them from top to bottom",
    when: "If the message contains",
    reply: "answer",
    fallback: "If nothing fits, answer",
    add: "Add a rule",
    remove: "Remove rule {n}",
    chat: "Test chat",
    placeholder: "Write to your bot…",
    send: "Send",
    matched: "rule {n} fired",
    noMatch: "no rule fired — default answer",
    code: "The same bot in Python",
    rules: [
      { when: "price", reply: "Our prices start at $50. Want the full list?" },
      { when: "hours", reply: "We work every day from 9:00 to 18:00." },
    ],
    defaultFallback: "Sorry, I didn't get that. Try asking about the price or our hours.",
  },
  amount: {
    title: "How a bot understands “100 usd”",
    label: "Type an amount, the way a person would",
    cleaned: "1. Tidy up: small letters, single spaces",
    number: "2. Look for a number",
    currency: "3. Look for a currency word",
    result: "4. What the bot understood",
    none: "not found",
    ok: "Amount {amount}, currency {currency}. Now the bot can work with it.",
    askNumber: "There is no number, so the bot asks: “How much?”",
    askCurrency: "There is no currency, so the bot asks: “Which currency?”",
  },
  quiz: {
    title: "Check yourself",
    correct: "Correct!",
    wrong: "Not quite.",
    score: "{n} of {total} correct",
  },
};

export type DemoStrings = typeof en;

const ru: DemoStrings = {
  demo: "Попробуйте",
  flow: {
    title: "Путешествие сообщения",
    pick: "Какое сообщение отправить",
    stations: { you: "Вы", telegram: "Telegram", bot: "Сервер бота", db: "База данных" },
    prev: "Назад",
    next: "Следующий шаг",
    play: "Запустить",
    pause: "Пауза",
    restart: "Сначала",
    step: "Шаг {n} из {total}",
    messages: [
      { text: "/start", reply: "Здравствуйте! Я бот магазина. Выберите: 🛒 Каталог · 📞 Связаться", rule: "команда /start → приветствие с кнопками" },
      { text: "100 usd", reply: "100 USD — понял. В какую валюту перевести?", rule: "число + слово-валюта → сумма" },
      { text: "Привет!", reply: "Привет! Напишите /start, и я покажу, что умею.", rule: "ни одно правило не подошло → вежливый ответ по умолчанию" },
    ],
    steps: [
      "Вы нажимаете «Отправить». Телефон отправляет текст на серверы Telegram — не напрямую боту.",
      "Telegram упаковывает текст в «обновление» (update): кто написал, из какого чата, когда. И передаёт его серверу бота.",
      "Бот заглядывает в свой блокнот — базу данных: кто этот человек, на каком языке говорит, что делал в прошлый раз?",
      "Теперь решает код бота. Он проверяет свои правила сверху вниз и берёт первое подходящее.",
      "Бот просит Telegram доставить ответ: вызывает метод sendMessage с номером чата и текстом.",
      "Telegram доставляет ответ на ваш телефон. Обычно всё это занимает меньше секунды.",
    ],
  },
  playground: {
    title: "Соберите своего бота",
    rulesLabel: "Правила — бот проверяет их сверху вниз",
    when: "Если в сообщении есть",
    reply: "ответить",
    fallback: "Если ничего не подошло, ответить",
    add: "Добавить правило",
    remove: "Удалить правило {n}",
    chat: "Проверочный чат",
    placeholder: "Напишите своему боту…",
    send: "Отправить",
    matched: "сработало правило {n}",
    noMatch: "ни одно правило не сработало — ответ по умолчанию",
    code: "Этот же бот на Python",
    rules: [
      { when: "цена", reply: "Наши цены — от 500 сомони. Прислать полный список?" },
      { when: "время", reply: "Мы работаем каждый день с 9:00 до 18:00." },
    ],
    defaultFallback: "Извините, я не понял. Спросите про цену или время работы.",
  },
  amount: {
    title: "Как бот понимает «100 usd»",
    label: "Напишите сумму, как написал бы человек",
    cleaned: "1. Навести порядок: маленькие буквы, одиночные пробелы",
    number: "2. Найти число",
    currency: "3. Найти слово-валюту",
    result: "4. Что понял бот",
    none: "не найдено",
    ok: "Сумма {amount}, валюта {currency}. Теперь бот может с этим работать.",
    askNumber: "Числа нет — бот переспросит: «Сколько?»",
    askCurrency: "Валюты нет — бот переспросит: «В какой валюте?»",
  },
  quiz: {
    title: "Проверьте себя",
    correct: "Верно!",
    wrong: "Не совсем.",
    score: "Правильно: {n} из {total}",
  },
};

const tj: DemoStrings = {
  demo: "Санҷед",
  flow: {
    title: "Сафари паём",
    pick: "Кадом паёмро фиристем",
    stations: { you: "Шумо", telegram: "Telegram", bot: "Сервери бот", db: "Пойгоҳи додаҳо" },
    prev: "Ба қафо",
    next: "Қадами навбатӣ",
    play: "Оғоз",
    pause: "Таваққуф",
    restart: "Аз нав",
    step: "Қадами {n} аз {total}",
    messages: [
      { text: "/start", reply: "Салом! Ман боти мағоза ҳастам. Интихоб кунед: 🛒 Каталог · 📞 Тамос", rule: "фармони /start → саломомадед бо тугмаҳо" },
      { text: "100 usd", reply: "100 USD — фаҳмидам. Ба кадом асъор табдил диҳам?", rule: "рақам + номи асъор → маблағ" },
      { text: "Салом!", reply: "Салом! /start нависед, ман нишон медиҳам, ки чӣ кор карда метавонам.", rule: "ягон қоида мувофиқ нашуд → ҷавоби пешфарз" },
    ],
    steps: [
      "Шумо «Фиристодан»-ро пахш мекунед. Телефон матнро ба серверҳои Telegram мефиристад — на мустақим ба бот.",
      "Telegram матнро ба «навсозӣ» (update) мепечонад: кӣ навишт, аз кадом чат, кай. Ва онро ба сервери бот медиҳад.",
      "Бот ба дафтарчаи худ — пойгоҳи додаҳо нигоҳ мекунад: ин шахс кист, бо кадом забон гап мезанад, бори охир чӣ кард?",
      "Акнун коди бот қарор медиҳад. Қоидаҳояшро аз боло ба поён месанҷад ва аввалинеро, ки мувофиқ аст, мегирад.",
      "Бот аз Telegram хоҳиш мекунад, ки ҷавобро расонад: усули sendMessage-ро бо рақами чат ва матн даъват мекунад.",
      "Telegram ҷавобро ба телефони шумо мерасонад. Одатан ҳамаи ин камтар аз як сония вақт мегирад.",
    ],
  },
  playground: {
    title: "Боти худро созед",
    rulesLabel: "Қоидаҳо — бот онҳоро аз боло ба поён месанҷад",
    when: "Агар дар паём бошад",
    reply: "ҷавоб диҳад",
    fallback: "Агар ҳеҷ чиз мувофиқ нашавад, ҷавоб диҳад",
    add: "Қоида илова кунед",
    remove: "Қоидаи {n}-ро нест кунед",
    chat: "Чати санҷишӣ",
    placeholder: "Ба боти худ нависед…",
    send: "Фиристодан",
    matched: "қоидаи {n} кор кард",
    noMatch: "ягон қоида кор накард — ҷавоби пешфарз",
    code: "Ҳамин бот бо Python",
    rules: [
      { when: "нарх", reply: "Нархҳои мо аз 500 сомонӣ сар мешаванд. Рӯйхати пурраро фиристам?" },
      { when: "вақт", reply: "Мо ҳар рӯз аз соати 9:00 то 18:00 кор мекунем." },
    ],
    defaultFallback: "Бубахшед, нафаҳмидам. Дар бораи нарх ё вақти кор пурсед.",
  },
  amount: {
    title: "Бот «100 usd»-ро чӣ тавр мефаҳмад",
    label: "Маблағро ҳамон тавре нависед, ки одам менависад",
    cleaned: "1. Тартиб додан: ҳарфҳои хурд, як фосила",
    number: "2. Рақамро ёфтан",
    currency: "3. Номи асъорро ёфтан",
    result: "4. Бот чиро фаҳмид",
    none: "ёфт нашуд",
    ok: "Маблағ {amount}, асъор {currency}. Акнун бот бо он кор карда метавонад.",
    askNumber: "Рақам нест — бот мепурсад: «Чанд?»",
    askCurrency: "Асъор нест — бот мепурсад: «Бо кадом асъор?»",
  },
  quiz: {
    title: "Худро санҷед",
    correct: "Дуруст!",
    wrong: "На он қадар.",
    score: "Дуруст: {n} аз {total}",
  },
};

export const demoStrings: Record<Locale, DemoStrings> = { en, ru, tj };
